### ISSUE TITLE
fix_healthcheck

### ISSUE THREAD

**Issue by username-rand** [blocklessnetwork/b7s#176]
Errors appear in the log when a healthcheck response contains "code":"200" instead of "code":200.  Json cannot unmarshal the code with quotes around the number.  This fix removes the quotes around the number for the Healthcheck message.  This is the diff file for node/process.go that will remove the quotes when found.

diff process.go.orig process.go
6a7
> 	"bytes"
73a75,82
> 	       code := []byte("\\"code\\":\\"")
> 	       index := bytes.Index(payload, code) + 7
> 	       if index > 6 {	// if 6 then code not found
> 	         copy(payload[index:],payload[index+1:]) // remove first quote
> 	         index += bytes.IndexByte(payload[index:],'"')
> 	         copy(payload[index:],payload[index+1:]) // remove second quote
> 	         payload = payload[:index+1]	// truncate payloag
> 	        }

[diff.process.go.txt](https://github.com/user-attachments/files/17970891/diff.process.go.txt)

**Comment by dmikey** [comment]
Can you open as a PR?
